FROM docker.sieve.com.br/b2wads/node:6.14.4-b2wads

COPY . /var/current

RUN chmod +x wait

RUN npm install --production

# ENV AMERICANAS_API
# ENV AWS_ACCESS_KEY_ID
# ENV AWS_SECRET_ACCESS_KEY
# ENV B2W_PROXY_API_HOST
# ENV BI_INTERFACE_HOST
# ENV BI_INTERFACE_TIMEOUT
# ENV BI_INTERFACE_TTL
# ENV BILLING_API_CACHE_TTL
# ENV BILLING_API_HOST
# ENV BILLING_API_TIMEOUT
# ENV LOGGER_LEVEL
# ENV MAX_CPCSUGGESTION_SELLER
# ENV MAX_CPCSUGGESTION_SUPPLIER
# ENV MONGODB_URL
# ENV NEW_RELIC_ENV_NAME
# ENV NEW_RELIC_LICENSE_KEY
# ENV NODE_ENV
# ENV PUBLISH_LIMIT
# ENV PUBLISHER_EXCHANGE
# ENV PUBLISHER_ROUTE
# ENV QUEUE_ACCOUNTS
# ENV QUEUE_ACCOUNTS_OPTIONS
# ENV RABBIT_URL
# ENV REDIS_PREFIX
# ENV REDIS_SCALE_READS
# ENV REDIS_TYPE
# ENV REDIS_URL
# ENV ROI_CPCSUGGESTION_SELLER
# ENV ROI_CPCSUGGESTION_SUPPLIER
# ENV SHOPTIME_API
# ENV SQL_PRIMARY_URL
# ENV SQL_SECONDARY_URL
# ENV STATS_API_CACHE_TTL
# ENV STATS_API_HOST
# ENV STATS_API_TIMEOUT
# ENV SUBMARINO_API
# ENV WORKER
# ENV WORKER_FORK


CMD ["npm", "start"]